version: 2
jobs:

  build:
    docker:
      - image: paulinhu/netcore-docker-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      
      - setup_remote_docker

      - run: docker build . --rm --no-cache -t $DOCKER_IMAGE_NAME_WITH_REGISTRY

      - run: echo DOCKER_REGISTRY_SERVER_PASSWORD | docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME --password-stdin

      - run: docker push $DOCKER_IMAGE_NAME_WITH_REGISTRY


workflows:
  version: 2
  build_and_test:
    jobs:
      - build