version: 2
jobs:

  build:
    docker:
      # TODO: change image to one that contains both dotnet SDK and docker client
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: docker build . --rm --no-cache -t $DOCKER_IMAGE_NAME_WITH_REGISTRY
      - run: |
          docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME -p $DOCKER_REGISTRY_SERVER_PASSWORD
          docker push $DOCKER_IMAGE_NAME_WITH_REGISTRY



workflows:
  version: 2
  build_and_test:
    jobs:
      - build