version: 2
jobs:

  build:
    docker:
      - image: paulinhu/netcore-docker-build
    steps:
      - checkout
      
      - setup_remote_docker
      - run: |
	    IMAGE_WITH_TAG=$DOCKER_IMAGE_NAME_WITH_REGISTRY:beta
            docker build . --rm --no-cache -t $IMAGE_WITH_TAG
            docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME -p $DOCKER_REGISTRY_SERVER_PASSWORD 
            docker push $IMAGE_WITH_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
