version: 2
jobs:

  build:
    docker:
      - image: paulinhu/netcore-docker-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      
      - run: service docker start

      - run: docker build . -t $DOCKER_IMAGE_NAME_WITH_REGISTRY

      - run: docker login $DOCKER_REGISTRY_URI -u $DOCKER_REGISTRY_SERVER_USERNAME -p $DOCKER_REGISTRY_SERVER_PASSWORD

      - run: docker push $DOCKER_IMAGE_NAME_WITH_REGISTRY


workflows:
  version: 2
  build_and_test:
    jobs:
      - build